[build]
    publish = "public/"

[functions]
    directory = "functions"

[[redirects]]
    from = "/cors/beat-savior/*"
    to = "https://beat-savior.herokuapp.com/api/livescores/player/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/cors/steamcommunity/*"
    to = "https://steamcommunity.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/cors/steamapi/*"
    to = "https://api.steampowered.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/cors/blapi/*"
    to = "https://api.beatleader.xyz/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = '/build/*'
    to = '/build/:splat'
    status = 200

[[redirects]]
    from = '/assets/*'
    to = '/assets/:splat'
    status = 200

[[redirects]]
    from = '/screenshot/*'
    to = 'https://voluble-kringle-cf6063.netlify.app/screenshot/:splat'
    status = 200

[[redirects]]
    from = '/robots.txt'
    to = '/robots.txt'
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = true